const {chromium}=require('playwright'),{spawn}=require('node:child_process'),{once}=require('node:events'),fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..'),report={status:'running',checks:[],errors:[]},check=(name,value,details)=>{assert.ok(value,name+' '+JSON.stringify(details||''));report.checks.push({name,status:'passed',details});};
(async()=>{const server=spawn(process.execPath,['server/local.mjs'],{cwd:root,env:{...process.env,PORT:'8787'},stdio:['ignore','pipe','pipe']});await once(server.stdout,'data');
let browser;try{browser=await chromium.launch({headless:true,...(process.env.BOOM_CHROMIUM?{executablePath:process.env.BOOM_CHROMIUM,args:JSON.parse(process.env.BOOM_CHROMIUM_ARGS||'[]')}: {})});
const pages=[];
for(let i=0;i<2;i++){const context=await browser.newContext({viewport:{width:600,height:650},hasTouch:true}),page=await context.newPage();pages.push(page);page.on('pageerror',e=>report.errors.push(e.stack));page.on('console',m=>{if(m.type()==='error')report.errors.push(m.text());});await page.route('http://boom.test/**',route=>{const p=new URL(route.request().url()).pathname,file=path.join(root,p==='/'?'index.html':p);return route.fulfill({path:file,contentType:({'.html':'text/html','.js':'text/javascript','.wasm':'application/wasm','.json':'application/json','.glb':'model/gltf-binary','.css':'text/css','.png':'image/png','.webp':'image/webp','.mp3':'audio/mpeg'})[path.extname(file)]||'application/octet-stream'});});await page.goto('http://boom.test/?debug=1&server=http://127.0.0.1:8787&room=verification');await page.waitForFunction(()=>window.__BOOM__?.battle.ready,null,{timeout:30000});await page.evaluate(()=>__BOOM__.pause());}
const [a,b]=pages;
for(const page of pages)await page.evaluate(()=>{const g=__BOOM__,receive=g.battle.receive.bind(g.battle);g.testEvents=[];g.battle.receive=m=>{receive(m);if(m.id===g.battle.id&&['damage','respawn'].includes(m.type))g.testEvents.push({type:m.type,hp:m.hp,enabled:g.body.isEnabled(),visible:g.vehicle.container.visible});};});
const step=async(page,n=3,fire=false)=>page.evaluate(({n,fire})=>{const g=__BOOM__,remote=[...g.battle.remotes.values()][0];let mouse={x:0,y:0};if(remote){const p=remote.group.position.clone();p.y+=.15;p.project(g.camera);mouse={x:p.x,y:p.y};}g.step(n,{drive:{x:0,z:0,handbrake:true},mode:'mouse',mouse,fire});},{n,fire});
const advance=async(ms,fire=false)=>{const until=Date.now()+ms;while(Date.now()<until){await step(a,3,fire);await step(b);await new Promise(r=>setTimeout(r,35));}};
await advance(2400);const initial=await a.evaluate(()=>({peers:__BOOM__.battle.remotes.size,models:[...__BOOM__.battle.remotes.values()].filter(r=>r.model).length,self:__BOOM__.battle.self,tag:[...__BOOM__.battle.remotes.values()][0].tag.textContent}));
check('Two independent browser sessions join one room and load actual remote car/health',initial.peers===1&&initial.models===1&&initial.self.hp===100,initial);
await advance(1800,true);const after=await b.evaluate(()=>({hp:__BOOM__.battle.self.hp,dead:__BOOM__.battle.dead,body:__BOOM__.body.isEnabled()}));const seen=await a.evaluate(()=>[...__BOOM__.battle.remotes.values()][0].hp);
check('Real gun input damages the other browser with matching server health',after.hp<100&&after.hp===seen,{victim:after,shooterSees:seen});
await b.evaluate(()=>__BOOM__.battle.send({type:'damage',hp:1000}));await advance(200);check('Forged client damage is ignored',await b.evaluate(()=>__BOOM__.battle.self.hp)<=100);
const deadline=Date.now()+10000;while(Date.now()<deadline&&await b.evaluate(()=>!__BOOM__.testEvents.some(e=>e.type==='damage'&&e.hp===0)))await advance(350,true);const dead=await b.evaluate(()=>__BOOM__.testEvents.find(e=>e.type==='damage'&&e.hp===0)||{hp:__BOOM__.battle.self.hp});
check('Destroyed car disables driving and disappears during respawn countdown',dead.hp===0&&!dead.enabled&&!dead.visible,dead);
if(!await b.evaluate(()=>__BOOM__.testEvents.some(e=>e.type==='respawn')))await advance(5400);check('Server respawns the player at full health on both clients',await b.evaluate(()=>__BOOM__.battle.self.hp===100&&__BOOM__.body.isEnabled())&&await a.evaluate(()=>[...__BOOM__.battle.remotes.values()][0].hp===100));
await advance(250);const scores=await Promise.all(pages.map(p=>p.evaluate(()=>({kills:__BOOM__.battle.self.kills,text:document.getElementById('player-kills').textContent}))));check('Server-confirmed kill appears only on the attacker HUD',scores[0].kills===1&&scores[0].text==='القتل ١'&&scores[1].kills===0&&scores[1].text==='القتل ٠',scores);
check('Identity effect belongs only to the local car',await a.evaluate(()=>__BOOM__.scene.children.filter(n=>n.name==='local-player-highlight').length===1&&[...__BOOM__.battle.remotes.values()].every(r=>!r.group.getObjectByName('local-player-highlight'))));
await a.evaluate(()=>__BOOM__.battle.drop());await advance(300);const crates=await Promise.all(pages.map(p=>p.evaluate(()=>[...__BOOM__.battle.crateMeshes.keys()])));check('Rear crate appears with the same ID on both clients',crates[0].length===1&&JSON.stringify(crates[0])===JSON.stringify(crates[1]),crates);
await a.evaluate(()=>__BOOM__.battle.drop());await advance(200);check('Crate cooldown rejects repeated drops',await a.evaluate(()=>__BOOM__.battle.crateMeshes.size===1));
const before=await a.evaluate(()=>__BOOM__.battle.self.hp);await a.click('#reset');await advance(300);check('Recover button does not heal the player',await a.evaluate(()=>__BOOM__.battle.self.hp)===before);
await b.reload();await b.waitForFunction(()=>window.__BOOM__?.battle.ready,null,{timeout:30000});await b.evaluate(()=>__BOOM__.pause());await advance(300);check('Reload reconnects without a duplicate remote car',await a.evaluate(()=>__BOOM__.battle.remotes.size===1));
await a.screenshot({path:path.join(root,'multiplayer-preview.png')});
await advance(10400);check('Crate expires and original Motri fireball runs without shader errors',await a.evaluate(()=>__BOOM__.battle.crateMeshes.size===0)&&report.errors.length===0,report.errors);
report.status='passed';report.environment='Two Chromium browser contexts connected to the real local WebSocket adapter with server-owned battle state; not an Internet or physical-phone latency measurement.';
}finally{if(browser)await browser.close();server.kill('SIGTERM');}
fs.writeFileSync(path.join(root,'verification/multiplayer-results.json'),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report,null,2));})().catch(error=>{report.status='failed';report.failure=error.stack;fs.writeFileSync(path.join(root,'verification/multiplayer-results.json'),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report,null,2));process.exit(1)});
